### ISSUE TITLE
Продумать админка и добавление пользователей с правами админа

### ISSUE THREAD

**Issue by Pronich** [netology-code/netomerch-backend#18]
Нужно продумать и изучить, как сделать добавление пользователей с правами админа.

**Comment by Apodisation13** [comment]
Если я создал хотя бы 1 суперюзера (админа) через python manage.py createsuperuser, потом я захожу в админку, там могу создавать пользователей и присваивать им статусы
1 - staff status - Designates whether the user can log into this admin site.  (по сути это Админ)
2 - superuser - Designates that this user has all permissions without explicitly assigning them.  (а вот это что-то не очень понятно)
